// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowMate.Models;

public partial class Adoption
{
    public int AdoptionId { get; set; }

    public int CustomerId { get; set; }

    public int TreeId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? OrderId { get; set; }

    public int FarmerId { get; set; }

    public string ProductName { get; set; }

    public int Years { get; set; }

    public string PrimaryImageUrl { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<MonthlyReport> MonthlyReports { get; set; } = new List<MonthlyReport>();

    public virtual Order Order { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Tree Tree { get; set; }
}