// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowMate.Repositories.Models;

public partial class Camera
{
    public int CameraId { get; set; }

    public int TreeId { get; set; }

    public string RtmpUrl { get; set; }

    public string HlsUrl { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Tree Tree { get; set; }
}