// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowMate.Models;

public partial class CartItem
{
    public int CartItemId { get; set; }

    public int CartId { get; set; }

    public int? ProductId { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? ListingId { get; set; }

    public int? TreeQuantity { get; set; }

    public decimal? TreeUnitPrice { get; set; }

    public int? TreeYears { get; set; }

    public virtual Cart Cart { get; set; }

    public virtual TreeListing Listing { get; set; }

    public virtual Product Product { get; set; }
}