// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowMate.Repositories.Models;

public partial class Customer
{
    public int CustomerId { get; set; }

    // New explicit FK to Users
    public int UserId { get; set; }

    public string ShippingAddress { get; set; }

    public decimal? WalletBalance { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Adoption> Adoptions { get; set; } = new List<Adoption>();

    // Rename to a clearer navigation name
    public virtual User User { get; set; }
}