// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowMate.Repositories.Models;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string ShippingAddress { get; set; }

    public decimal? WalletBalance { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Adoption> Adoptions { get; set; } = new List<Adoption>();

    public virtual User CustomerNavigation { get; set; }
}