// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowMate.Models;

public partial class Farmer
{
    public int FarmerId { get; set; }

    public int UserId { get; set; }

    public string FarmName { get; set; }

    public string FarmAddress { get; set; }

    public string ContactPhone { get; set; }

    public string VerificationStatus { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<MonthlyReport> MonthlyReports { get; set; } = new List<MonthlyReport>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<TreeListing> TreeListings { get; set; } = new List<TreeListing>();

    public virtual User User { get; set; }
}