// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowMate.Models;

public partial class OrderItem
{
    public int OrderItemId { get; set; }

    public int OrderId { get; set; }

    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public decimal UnitPrice { get; set; }

    public int Quantity { get; set; }

    public decimal? TotalPrice { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? ListingId { get; set; }

    public int? TreeQuantity { get; set; }

    public decimal? TreeUnitPrice { get; set; }

    public decimal? TreeTotalPrice { get; set; }

    public virtual TreeListing Listing { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
}