// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowMate.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int CustomerId { get; set; }

    public int SellerId { get; set; }

    public string ShipFullName { get; set; }

    public string ShipPhone { get; set; }

    public string ShipAddress { get; set; }

    public string ShipCity { get; set; }

    public string ShipState { get; set; }

    public string ShipPostalCode { get; set; }

    public string ShipCountry { get; set; }

    public decimal Subtotal { get; set; }

    public decimal ShippingFee { get; set; }

    public decimal TotalAmount { get; set; }

    public string Currency { get; set; }

    public string Status { get; set; }

    public string PaymentStatus { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string OrderType { get; set; }

    public virtual ICollection<Adoption> Adoptions { get; set; } = new List<Adoption>();

    public virtual Customer Customer { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Farmer Seller { get; set; }

    public virtual ICollection<Shipment> Shipments { get; set; } = new List<Shipment>();
}