// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowMate.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int? AdoptionId { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public string TransactionReference { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? OrderId { get; set; }

    public string SourceType { get; set; }

    public DateTime? PaidAt { get; set; }

    // Sepay integration fields
    public string PaymentGateway { get; set; }

    public string GatewayOrderCode { get; set; }

    public string QrContent { get; set; }

    public string QrImageUrl { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public string WebhookSignature { get; set; }

    public DateTime? WebhookReceivedAt { get; set; }

    public string GatewayRawPayload { get; set; }

    public string ErrorCode { get; set; }

    public string ErrorMessage { get; set; }

    public virtual Adoption Adoption { get; set; }

    public virtual Order Order { get; set; }
}