// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowMate.Repositories.Models;

public partial class Post
{
    public int PostId { get; set; }

    public int FarmerId { get; set; }

    public string ProductName { get; set; }

    public string ProductType { get; set; }

    public string ProductVariety { get; set; }

    public string FarmName { get; set; }

    public string Origin { get; set; }

    public decimal PricePerYear { get; set; }

    public decimal? HarvestWeight { get; set; }

    public string Unit { get; set; }

    public int? HarvestFrequency { get; set; }

    public int TreeQuantity { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Farmer Farmer { get; set; }

    public virtual ICollection<Medium> Media { get; set; } = new List<Medium>();

    public virtual ICollection<PostComment> PostComments { get; set; } = new List<PostComment>();

    public virtual TreeListing TreeListing { get; set; }
}