// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowMate.Models;

public partial class Tree
{
    public int TreeId { get; set; }

    public int ListingId { get; set; }

    public string UniqueCode { get; set; }

    public string Description { get; set; }

    public string Coordinates { get; set; }

    public string HealthStatus { get; set; }

    public string AvailabilityStatus { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Adoption> Adoptions { get; set; } = new List<Adoption>();

    public virtual Camera Camera { get; set; }

    public virtual TreeListing Listing { get; set; }
}