// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowMate.Models;

public partial class TreeListing
{
    public int ListingId { get; set; }

    public int PostId { get; set; }

    public int FarmerId { get; set; }

    public decimal PricePerTree { get; set; }

    public int TotalQuantity { get; set; }

    public int AvailableQuantity { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Farmer Farmer { get; set; }

    public virtual Post Post { get; set; }

    public virtual ICollection<Tree> Trees { get; set; } = new List<Tree>();
}