// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowMate.Models;

public partial class Medium
{
    public int MediaId { get; set; }

    public int? PostId { get; set; }

    public int? ReportId { get; set; }

    public string MediaUrl { get; set; }

    public string MediaType { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Post Post { get; set; }

    public virtual MonthlyReport Report { get; set; }
}