// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowMate.Models;

public partial class MonthlyReport
{
    public int ReportId { get; set; }

    public int AdoptionId { get; set; }

    public int FarmerId { get; set; }

    public int ReportMonth { get; set; }

    public int ReportYear { get; set; }

    public string Activities { get; set; }

    public string Notes { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? PublishedAt { get; set; }

    public virtual Adoption Adoption { get; set; }

    public virtual Farmer Farmer { get; set; }

    public virtual ICollection<Medium> Media { get; set; } = new List<Medium>();
}