name: Build and deploy ASP.Net Core app to Azure Web App - GrowMate

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Optional caching to speed up restore
      - name: Cache .NET packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Restore and build only the Web API project
      - name: Restore dependencies
        run: dotnet restore GrowMate/GrowMateWebAPIs.csproj

      - name: Build GrowMate Web API
        run: dotnet build GrowMate/GrowMateWebAPIs.csproj --configuration Release --no-restore

      # Publish the Web API to an output folder
      - name: Publish GrowMate Web API
        run: dotnet publish GrowMate/GrowMateWebAPIs.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-build

      # Upload artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./myapp

      - name: Set ASPNETCORE_ENVIRONMENT to Production
        run: echo "ASPNETCORE_ENVIRONMENT=Production" >> $GITHUB_ENV

      # Optional: Ensure Azure CLI is available
      - name: Log in to Azure CLI
        uses: azure/login@v2
        with:
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2D0D690E3911430E918029CC17701F5E }}

      # ✅ Set the correct startup command (fixes runtime confusion)
      - name: Set startup command
        run: |
          az webapp config set \
            --name GrowMate \
            --resource-group GrowMate \
            --startup-file "dotnet GrowMateWebAPIs.dll"

      # Deploy the Web API to Azure App Service
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GrowMate'
          slot-name: 'Production'
          package: ./myapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2D0D690E3911430E918029CC17701F5E }}
